### ISSUE TITLE
Resource Link

### ISSUE THREAD

**Issue by ardauzunoglu** [shuyanzhou/wikihow_hierarchy#1]
Hi. Firstly, thanks for making such an amazing work open source. 

I was trying to reproduce the results and train the re-ranking model using the cmd code shared in the README.md. Unfortunately, it didn't start training due to the lacking files in the "data" folder. I also couldn't download the resources due to the link in Resources section giving 404 - Page Not Found error. My question is how can I access and download those resources to train the re-ranking model?

Thanks.

**Comment by shuyanzhou** [comment]
Hi, thanks for your interest in our work. I somehow forgot the data link. I have updated it in the README file. Please check and feel free to drop any more questions.
